# Adm ed242
version: '2.4'
services: 
  streamlit-boss-ed242:
    image: joserochabh/streamlit-sqlite3:1.8.0
    ports:
      - '3232:3232'
    networks:
      - "web"
    volumes:
      #- './data:/usr/src/app/data:delegated'
      - './project:/usr/src/app/project'
      - '/etc/localtime:/etc/localtime:ro'
        #    labels:
        #      - "traefik.enable=true"
        #      - "traefik.docker.network=web"
        #      - "traefik.http.routers.streamlit-up.entrypoints=web"
        #      - "traefik.http.routers.streamlit-up.rule=Host(`adrep242.rocha.tec.br`)"
      # Letsencrypt secure
      #      - "traefik.http.routers.streamlit-up_secure.entrypoints=web-secure"
      #      - "traefik.http.routers.streamlit-up_secure.tls.certresolver=myhttpchallenge"
      #      - "traefik.http.routers.streamlit-up_secure.rule=Host(`adrep242.rocha.tec.br`)"
    command: ["streamlit","run","project/app_adm_main.py","--server.port","3232"]
    
networks:
    web:
      external: true
